connection:
  web:
    type: web
    timeout: 10
    browser: FIREFOX
    #browser: Chrome
    default_element_wait: 10
    default_timeout: 60
    auto_download: {
      dir: '/home/vagrant/Downloads/',
      types: ['application/x-gzip','config/conf']
    }

  web1:
    type: web
    timeout: 10
    browser: Chrome
    default_element_wait: 10
    default_timeout: 60
    auto_download: {
      dir: '/home/vagrant/Downloads/',
      types: ['application/x-gzip','config/conf']
    }

  n1:
    prompt: ['~ #', '#', '>']
    ip: 10.5.182.210
    port: 4001
    protocol: telnet
    timeout: 30
    type: linux
    user: admin
    password: admin
    login_prompt: 'User Name'
    password_prompt: 'Password'
    vlan: 913
    incorrect_vlan: 999
    priority: 1
    Bonding_line1: line8
    Bonding_line2: line9
    #apc_outlet: 4
    apc_outlet: 7
    Submask: 255.255.255.0

  console:
    prompt: ['Password OK']
    login_prompt: 'Username'
    password_prompt: 'Password:'
    user: 'lab'
    password: 'lab'
    vendor: console
    ip: 10.5.161.198
    port: 2033
    protocol: telnet
    timeout: 30
    type: linux
    gateway: 10.5.161.254
    gateway2: 172.18.18.10

  cisco:
    prompt: ['Password OK', 'C1801', 'C1801>', 'C1801#', 'C1801(config)#', 'C1801(config-if)#', 'C1801(config-if-range)#', 'C1801(config-line)#']
    login_prompt: 'Username'
    password_prompt: 'Password:'
    user: 'lab'
    password: 'lab'
    vendor: cisco
    hostname: C1801
    ip: 10.5.161.198
    port: 2035
    protocol: telnet
    timeout: 30
    type: linux
    ethernet_port_number: 
    ipv6_ip: 2222::1
    ipv6_mask: 64
    gateway: 10.5.161.254
    gateway2: 172.18.18.10
    dhcp_pool_name: POOL_1
    ppoe_interface: Virtual-Template1
    vlan: Vlan10
    Fast_Ethernet_Port_Number: '2'

  cisco_LAN_Switch:
    prompt: ['Password OK', 'LAN-SW', 'LAN-SW>', 'LAN-SW#', 'LAN-SW(config)#', 'LAN-SW(config-if)#', 'LAN-SW(config-if-range)#', 'LAN-SW(config-line)#']
    login_prompt: 'Username'
    password_prompt: 'Password:'
    user: 'lab'
    password: 'lab'
    vendor: cisco_LAN_Switch
    hostname: LAN-SW
    ip: 10.5.161.198
    port: 2034
    protocol: telnet
    timeout: 30
    type: linux
    ethernet_port_number: 
    ipv6_ip: 2222::1
    ipv6_mask: 64
    gateway: 10.5.161.254
    gateway2: 172.18.18.10

  cisco2:
    prompt: ['Password OK', 'c2921-ipv6', 'c2921-ipv6>', 'c2921-ipv6#', 'c2921-ipv6(config)#', 'c2921-ipv6(config-if)#', 'c2921-ipv6(config-if-range)#', 'c2921-ipv6(config-line)#']
    login_prompt: 'Username'
    password_prompt: 'Password:'
    user: 'lab'
    password: 'lab'
    vendor: cisco2
    hostname: c2921-ipv6
    ip: 10.5.182.200
    port: 2002
    protocol: telnet
    timeout: 30
    type: linux
    ethernet_port_number: GigabitEthernet0/0
    ipv6_ip: 2222::1
    ipv6_mask: 64
    gateway: 172.18.100.2
    gateway2: 172.18.18.20
    dhcp_pool_name: AAA
    ppoe_interface: Virtual-Template1

  IPv6_Server:
   ip: 172.16.0.22
   timeout: 30
   type: linux
   protocol: telnet
   user: gemtek
   password: gemtek
   root_password: 'gemtek'
   prompt: ['gemtek@gemtek']
   interface: enp3s0

  terminal_server:
    prompt: ['Password:','ATS-TERMSERV>', 'ATS-TERMSERV#']
    password_prompt: 'Password:'
    user: 'lab'
    password: 'lab'
    ip: 10.5.161.198
    port: 23
    protocol: telnet
    timeout: 30
    type: linux

  DUT_WAN_Telnet:
    #ip: 10.5.182.195
    ip: 172.16.11.20
    timeout: 60
    type: linux
    protocol: telnet
    user: root
    password: 5/4jp6t03qup3
    #prompt: ['vagrant\@dual-wifi-client2\:\~\$']
    prompt: ['root@']
    #prompt: ['vagrant\@thomas-VPCEB37FW\:\~\$']

  DUT_LAN_SSH:
    ip: 192.168.1.1
    timeout: 60
    type: linux
    protocol: ssh
    user: root
    password: 5/4jp6t03qup3
    #prompt: ['vagrant\@dual-wifi-client2\:\~\$']
    prompt: ['root@']

  DUT_LAN_Telnet:
    #ip: 10.5.182.195
    ip: 192.168.1.1
    timeout: 60
    type: linux
    protocol: telnet
    user: root
    password: 5/4jp6t03qup3
    #prompt: ['vagrant\@dual-wifi-client2\:\~\$']
    prompt: ['root@']
    #prompt: ['vagrant\@thomas-VPCEB37FW\:\~\$']

  wifi_client:
    #ip: 10.5.182.195
    ip: 172.16.0.18
    timeout: 60
    type: linux
    protocol: telnet
    user_name: gemtek
    password: gemtek
    #prompt: ['vagrant\@dual-wifi-client2\:\~\$']
    prompt: ['gemtek@gemtek']
    #prompt: ['vagrant\@thomas-VPCEB37FW\:\~\$']
    int: wlp4s0
    int_5G: wlp4s0
    interface: wlp4s0
    hostname: lab-HP
    int_2_4g: wlp4s0
    MAC: f4:3b:d8:6e:e9:16


  wifi_client2:
    #ip: 10.5.182.195
    ip: 172.16.0.19
    #traffic_ip: 192.168.11.2
    timeout: 60
    type: linux
    protocol: telnet
    user_name: gemtek
    password: gemtek
    #prompt: ['vagrant\@dual-wifi-client2\:\~\$']
    prompt: ['gemtek@gemtek']
    #prompt: ['vagrant\@thomas-VPCEB37FW\:\~\$']
    int: wlp4s0
    interface: wlp4s0
    int_5G: wlp4s0
    hostname: lab-PC
    int_2_4g: wlp4s0
    MAC: f4:3b:d8:6e:ce:72
    

  wifi_client_5g:
    ip: 10.5.182.195
    timeout: 30
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    prompt: ['vagrant\@thomas-VPCEB37FW\:\~\$']
    int: wlan0
    hostname: thomas-VPCEB37FW
    int_2_4g: wlan0
    assign_static_ip: 192.168.1.199

  apc:
    #ip: 10.5.182.201
    ip: 10.5.182.206
    type: linux
    timeout: 30
    protocol: telnet
    type: apc
    user: apc
    password: apc
    login_prompt: 'User Name'
    password_prompt: 'Password'

  e5:
    ip: 10.5.182.207
    type: linux
    timeout: 30
    protocol: ssh
    user: root
    password: root
    prompt: ['root\@E5-PRO\:\~\#', 'E5-PRO\#']
    hostname: E5-PRO
    Bonding_gfast1: gfast8
    Bonding_gfast2: gfast9
    group_name: gbond4
    service_vlan1: 913
    service_vlan2: 914

  localhost:
    ip: 127.0.0.1
    traffic_ip: 192.168.11.61
    timeout: 30
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    root_password: vagrant
    prompt: ['vagrant\@buffalo-1']
    interface: eth2

  lanhost:
   ip: 172.16.0.52
   #traffic_ip: 192.168.11.61
   timeout: 30
   type: linux
   protocol: ssh
   user: vagrant
   password: vagrant
   root_password: '123456'
   prompt: ['vagrant@lanhost']
   interface: eth2

  lanhost2:
   ip: 172.16.0.20
   #traffic_ip: 192.168.11.61
   timeout: 60
   type: linux
   protocol: telnet
   user: gemtek
   password: gemtek
   root_password: gemtek
   prompt: ['gemtek@gemtek']
   interface: enp3s0


  lanhost_buffalo1:
    ip: 172.1.1.125
    traffic_ip: 192.168.11.150
    timeout: 30
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    root_password: vagrant
    prompt: ['vagrant@Buffalo-1-lanhost']
    interface: eth2

  lanhost_buffalo2:
      ip: 172.1.1.126
      traffic_ip: 192.168.11.151
      timeout: 30
      type: linux
      protocol: ssh
      user: vagrant
      password: vagrant
      root_password: vagrant
      prompt: ['vagrant@Buffalo-2-lanhost']
      interface: eth2

  lanhost_buffalo3:
      ip: 172.1.1.127
      traffic_ip: 192.168.11.152
      timeout: 30
      type: linux
      protocol: ssh
      user: vagrant
      password: vagrant
      root_password: vagrant
      prompt: ['vagrant@Buffalo-3-lanhost']
      interface: eth2

# 172.18.19.1 (dut ip) ...[MDU]... 172.18.19.2 (dhcp server ip) === 172.18.18.10 (gi0/2.1070 ip).....172.18.18.2 (wanhost ip)
  wanhost:
    ip: 172.16.0.71
    traffic_ip: 172.18.18.168
    timeout: 30
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    root_password: vagrant
    prompt: ['vagrant@WAN-host']
    interface: eth2
    route: 172.18.19.0
    route_mask: 255.255.255.0
    network_route: 172.18.18.0
    default_gw: 172.18.18.10
    Domain_Name_URL: www.google.com

  dut1:
    prompt: ['>', '#']
    #ip: 192.168.1.1
    ip: 192.168.11.1
    protocol: ssh
    timeout: 5
    type: linux
    user: cht
    password: 40wq3766
    wan_interface: veip0.1
    eth1: eth0.2
    eth2: eth0.3
    eth3: eth0.4
    eth4: eth0.5

  vm1:
    ip: 10.5.182.224
    timeout: 30
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    root_password: vagrant
    prompt: ['>', 'vagrant\@wacn-123 \~\]\$', 'vagrant\@wacn-123 tmp_fw\]\$']
    interface: eth2
    lan_ip: 192.168.1.177

  olt:
    ip: 172.1.1.103
    type: linux
    timeout: 30
    protocol: telnet
    user: isadmin
    password: ans#150
    login_prompt: 'login'
    password_prompt: 'password'
    prompt: ['typ\:isadmin\@Gemtek\>\#', 'typ\:isadmin\@Gemtek\>configure\>equipment\>ont\>interface\>1\/1\/2\/6\/10\#', 'typ\:isadmin\@Gemtek\>configure\>pon\>interface\>1\/1\/2\/6\#']
    ont_index: 1/1/2/6/10
    pon_index: 1/1/2/6

  dut_admini_new_passwd_ssh:
    prompt: ['$']
    ip: 192.168.1.1
    protocol: ssh
    timeout: 5
    type: linux
    user: cht
    password: adminitest

  dut_admini_new_passwd_telnet:
    ip: 192.168.1.1
    prompt: ['$']
    prompt: ['version']
    type: linux
    timeout: 30
    protocol: telnet
    user: cht
    password: adminitest
    login_prompt: 'I-040GW.cht.com.tw login'
    password_prompt: 'Password'

  dut_user_new_passwd_ssh:
    prompt: ['$']
    ip: 192.168.1.1
    protocol: ssh
    timeout: 5
    type: linux
    user: user
    password: usertest

  dut_user_new_passwd_telnet:
    ip: 192.168.1.1
    prompt: ['$']
    prompt: ['version']
    type: linux
    timeout: 30
    protocol: telnet
    user: user
    password: usertest
    login_prompt: 'I-040GW.cht.com.tw login'
    password_prompt: 'Password'

  radius_server:
    ip: 172.1.1.163
    traffic_ip: 172.18.18.169
    radius_port: 1812
    radius_key: 123456
    timeout: 30
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    root_password: vagrant
    prompt: ['vagrant\@freeradius-vm:\~\$']
    interface: eth1

  secom_switch:
    prompt: ['Password OK', 'office_net_switch>', 'office_net_switch\>', 'office_net_switch\#', 'office_net_switch\(config\)\#', 'office_net_switch\(config-if\)\#', 'Escape character is', ']']
    login_prompt: 'Username'
    password_prompt: 'Password:'
    user: 'lab'
    password: 'lab'
    vendor: cisco
    hostname: office_net_switch
    ip: 10.5.182.210
    port: 4009
    protocol: telnet
    timeout: 30
    type: linux
    vdsl_port_number: 0/3
    cht_port_number: 0/4
    gpon_port_number: 0/5
