global:
  g_input_enter: "\r"
  g_input_ctrl_c: "\x03"
  g_input_ctrl_d: "\x04"

  #----------n/s/h/s/tg vlan parameters here-----------
  g_n2_dpu_data_vlan: 1100
  g_n2_us_vlan: 1100
  g_n1_dpu_data_vlan: 1104
  g_n1_dpu_video_vlan: 1154
  g_n1_us_vlan: 1104


  g_h1_eth2_vlan: 75
  #----------------------------------------------------

  g_mgmt_vlan: 899

  g_ip_format: \d+\.\d+\.\d+\.\d+
  g_version_format: \d+\.\d+\.\d+\.\d+
  g_HWaddr_format: '[A-F0-9]{2}(:[A-F0-9]{2}){5}'

  g_dut_gui_url: http://192.168.66.1
  gui_url: 192.168.11.1
  g_dut_gui_user: sigmu
  g_dut_gui_pwd: secom
  g_dut_sn: CXNKEC4F827E7352
  g_dut_wait_time: 840

  g_dut_gw: 192.168.1.1
  #g_dut_gw: 192.168.11.1
  g_dut_priority: 0
  g_dut_vlan: 4082
  g_wifi_guest_gw: 192.168.67.1
  g_dut_gw_network: 192.168.55.0
  g_dut_gw_network_prefix: 192.168.55
  g_dut_ip_mask: 255.255.255.0
  g_dut_static_ipaddr: 172.16.11.210
  #g_dut_static_ipaddr2: 172.18.18.123
  g_dut_static_netmask: 255.255.255.0
  g_dut_static_gateway: 172.16.11.1
  #g_dut_static_gateway2: 172.18.100.2
  #g_dut_static_gateway3: 172.18.18.10
  g_dut_static_dns1: 172.16.11.1
  g_dut_static_dns2: 172.16.11.100
  g_dut_static_ip_segment: 172.18.19.
  g_dut_DNS_from_company: 168.95.1.1
  g_google_dns: 8.8.8.8
  g_dut_gw_dhcp_server_start_ip: 192.168.55.100
  g_dut_gw_dhcp_server_end_ip: 192.168.55.249
  #g_dut_reg: CHT_123acn_2.4G_reg
  g_dut_reg: Buffalo_F578_2.4G_reg
  g_dut_default_ssid: Buffalo-G-F578
  g_dut_ssid1: Buffalo_F578_2.4G_reg
  g_dut_ssid2: CHT_G040WQ_2.4G2
  g_dut_ssid3: CHT_G040WQ_2.4G3
  g_dut_ssid4: CHT_G040WQ_2.4G4
  g_dut_5g_ssid1: Buffalo_F578_5G_reg
  g_dut_5g_ssid2: Buffalo_F578_5G2
  g_dut_5g_ssid3: Buffalo_F578_5G3
  g_dut_5g_ssid4: Buffalo_F578_5G4
  g_dut_guest_ssid: DropAP-Guest-0bb778
  g_dut_repeater_ssid_pw: '12345678'
  g_dut_wep_key: '1234567890123'
  g_dut_dummy_ssid_pw: 12345678
  g_dut_wep_ssid_pw: 12345
  g_dut_pppoe_username: test
  g_dut_pppoe_password: test
  g_dut_invalid_pppoe_username: testwrong
  g_dut_invalid_pppoe_password: testwrong
  g_lanhost_lease_file: /var/lib/dhcp/dhclient.leases
  g_fw_folder: /home/vagrant/tmp_fw
  g_tftp_folder: /var/lib/tftpboot/
  l2tp_server_gui_url: http://192.168.1.200:1080
  g_dut_LAN_host_Prefix: '4444'
  g_dut_default_SLID: default
  g_dut_test_SLID: ONT1234567

  #---- GPON Parameters ----
  GPON_GW: https://192.168.1.1/
  Bufffalo_URL: http://192.168.11.1/
  Bufffalo_Password: 88888888
  Bufffalo_User: admin
  User: cht
  Password: 40wq3766
  Password_sh: 40wq9c66
  PPPoE_User: test
  PPPoE_Password: test
  lan_nameserver: 192.168.1.1
  g_dut_wan_int: veip0.1
  lan_static_ip: 192.168.1.66
  LAN_PC_MAC:
    - '08'
    - '00'
    - '27'
    - 'df'
    - 'c1'
    - '00'
  vpn_network_segment: 172.18.18
  new_administrator_password: adminitest
  new_user_password: usertest
  radius_user: gavin
  radius_password: gemtek
